version: "3.8"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:53:53" # only required for Pro
      - "127.0.0.1:53:53/udp" # only required for Pro
      - "127.0.0.1:443:443" # only required for Pro
      - "127.0.0.1:4510-4530:4510-4530" # only required for Pro
      - "127.0.0.1:4566-4597:4566-4597"
    environment:
      AWS_DEFAULT_REGION: us-east-1
      SERVICES: dynamodb,lambda,cloudformation,s3,apigateway,iam,route53,sts,cognito,es
      DATA_DIR: /tmp/localstack/data
      LAMBDA_EXECUTOR: docker
      DOCKER_HOST: unix:///var/run/docker.sock
      LAMBDA_DOCKER_NETWORK: host
      DEBUG: 1
    env_file:
      - .env.docker
    volumes:
      - "./tmp:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app_network

  globals:
    build:
      context: "."
      dockerfile: Dockerfile.globals
    command: yarn dev:docker
    depends_on:
      - localstack
    networks:
      - app_network
    volumes:
      - nodemodules:/app/node_modules

  api:
    build: "."
    command: bash -c "sleep 60; yarn dev:docker"
    depends_on:
      - localstack
      - globals
    networks:
      - app_network
    # environment:
    # SLS_DEBUG: "*"
    volumes:
      - ./:/app/
      - nodemodules:/app/node_modules
      - layers:/app/layers

volumes:
  database-data:
  nodemodules:
  layers:

networks:
  app_network:
    driver: bridge
