version: "3.8"

services:
  docker-events-listener:
    container_name: base-project-serverless-localstack_docker-events-listener
    build:
      context: docker-events-listener-build
      dockerfile: Dockerfile # The Dockerfile from ./docker-events-listener-build
    networks:
      - app_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  localstack:
    image: localstack/localstack
    container_name: base-project-serverless-localstack_localstack
    ports:
      - "127.0.0.1:53:53" # only required for Pro
      - "127.0.0.1:53:53/udp" # only required for Pro
      - "127.0.0.1:443:443" # only required for Pro
      - "127.0.0.1:4510-4530:4510-4530" # only required for Pro
      - "4566-4597:4566-4597"
    environment:
      AWS_DEFAULT_REGION: us-east-1
      SERVICES: dynamodb,lambda,cloudformation,s3,apigateway,iam,route53,sts,ssm,secretsmanager
      DATA_DIR: /tmp/localstack/data
      LAMBDA_EXECUTOR: docker
      DOCKER_HOST: unix:///var/run/docker.sock
      LAMBDA_DOCKER_NETWORK: host
      EDGE_PORT: 4566
    env_file:
      - .env.docker
    volumes:
      - "./tmp:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app_network
    depends_on:
      - docker-events-listener

  api:
    build: "."
    container_name: base-project-serverless-localstack_api
    command: bash -c "sleep 20; yarn dev:docker"
    depends_on:
      - localstack
    ports:
      - 3000:3000
    networks:
      - app_network
    # environment:
    # SLS_DEBUG: "*"
    volumes:
      - ./:/app/
      - nodemodules:/app/node_modules
      - layers:/app/layers

volumes:
  nodemodules:
  layers:

networks:
  app_network:
    driver: bridge
