FROM node:14

WORKDIR /app

COPY ./package.json ./package.json
COPY ./yarn.lock ./yarn.lock

RUN yarn

# Copy files

ADD ./globals/serverless.ts ./serverless.ts
ADD ./tsconfig.json ./tsconfig.json
ADD ./tsconfig.paths.json ./tsconfig.paths.json

CMD yarn dev:docker
